### ISSUE TITLE
Red/Blue Block and Switch Block inconsistencies

### ISSUE THREAD

**Issue by Swiftshine** [Zenith-Team/Tsuru#24]
**Describe the bug**
The Red/Blue Block state does not always match that of the Switch Blocks themselves

**To Reproduce**
Simply place down a Red/Blue Block as red or blue and make sure it is different from the current Switch Block state.

**Expected behavior**
The colours of the Red/Blue block should always match with that of a Switch Block; if the Switch Block is blue then the red blocks should disappear and the blue blocks should appear, and vice versa

**Screenshots**
![image](https://user-images.githubusercontent.com/85366980/202911221-199e5de8-08e2-4823-9653-9a1e17563a50.png)

**System Information**
 - **Operating System**: Windows 10, 64 bit
 - **Cemu Version**: 1.26.2f
 - **Cemu Graphics API** (OpenGL or Vulkan?): Vullkan
 - **NSMBU Region** (US, EU or JP?): US

**Comment by Luminyx1** [comment]
Fixed in https://github.com/Zenith-Team/Tsuru/commit/99e3f5c8e4d2cdf855a75ce367cb1ba5f9ad7d16.
