### ISSUE TITLE
Instant respawn doesn't work

### ISSUE THREAD

**Issue by BaronStijn** [Zenith-Team/Tsuru#28]
**Describe the bug**
The instant respawn function doesn't do anything

**To Reproduce**
1. Set the 10th byte of ts_savedata.dat to 1
2. Die

**Expected behavior**
Getting booted to the level loading screen upon dead

**Screenshots**
![image](https://user-images.githubusercontent.com/79195369/207663954-c13e46be-d4f0-427b-be0e-e81ae1ca77c3.png)

**System Information**
 - **Operating System**:  Windows 11
 - **Cemu Version**: 1.22.2
 - **Cemu Graphics API** Vulkan
 - **NSMBU Region** EU

**Additional context**
My rom has been modified with random nonsense, like chages to level and model files

**Comment by Luminyx1** [comment]
Fixed in https://github.com/Zenith-Team/Tsuru/commit/05170f2653a1d0e989d9431080b68df18b4d23ea.
