### ISSUE TITLE
NSLU Luigi physics not being changed

### ISSUE THREAD

**Issue by techmuse8** [Zenith-Team/Tsuru#31]
**Describe the bug**
Whenever you play NSLU with the DLC installed, the Luigi physics don't apply, as Luigi jumps the same height as Mario normally would, and crouch jumping doesn't play the flutter animation as examples.

**To Reproduce**
1. Go to NSLU
2. Try to jump around, and you'll notice the physics would be the regular Mario physics

**Expected behavior**
The Luigi physics to apply, as it did in previous versions.

**Screenshots**

**System Information**
> Windows users: Please specify the Windows version (11, 10, 8.1, 8) and arch (32 or 64 bit?)
>
> Linux users: Please specify your distribution and arch (32 or 64 bit?)
 - **Windows 11 64-bit**
 - **Cemu 1.22.3b**
 - **Vulkan** 
 - **NSMBU Region** (US, EU or JP?): US

**Additional context**

**Comment by Luminyx1** [comment]
Fixed by https://github.com/Zenith-Team/Tsuru/commit/53c59925109507d1a9c8f358533d288ae563fd52
